### ISSUE TITLE
Crashing image

### ISSUE THREAD

**Issue by starseeker** [s-bear/image-hash#2]
When I adjust the code to compile, I am seeing a crash with the following image

https://github.com/BRL-CAD/brlcad/blob/main/src/tclscripts/archer/images/brep_union.png

Can you confirm whether you are seeing similar behavior?  It's possible I messed up a change when adjusting the code on my end, but I am able to hash somewhat larger images.

**Comment by starseeker** [comment]
Update - this appears to be related to using 128,128 to initialize the Preprocess class - if the image has a dimension smaller than that, it's trouble.

**Comment by s-bear** [comment]
Thanks for letting me know. I'm away for the weekend so I'll take a look at it in a couple days.

**Comment by s-bear** [comment]
I've fixed the resizing code. 

For posterity, it was a bad index into the tile size tables. When down-sampling, a tile of pixels is averaged together to make the single pixel in the smaller image. When up-sampling, the single pixel from the smaller image is copied across the tile in the larger image. The tile sizes are pre-computed by the Preprocess class using a variant of Bressenham's algorithm to uniformly distribute the unequal tile sizes. This specific bug was indexing into the list of tile heights using the y coordinate of the larger image rather than the smaller image when upsampling, leading to an out-of-bounds error.

Cheers,
Sam
